import Head from 'next/head';
import Image from 'next/image';
import {
  Box,
  Card,
  CardContent,
  CardMedia,
  Container,
  Grid,
  Typography,
} from '@mui/material';
import { cyan, green } from '@mui/material/colors';
import { getPhotos, rnmApiResult } from '@/lib/api';
import { useState } from 'react';

export default function Home({ data }: { data: rnmApiResult[] }) {
  const [images, setImages] = useState(data);
  return (
    <>
      <Head>
        <title>Rick & Morty Image Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box overflow="hidden" bgcolor="#011401" minHeight="100vh">
        <Container>
          <Typography
            color={cyan[300]}
            mb="1rem"
            textAlign="center"
            variant="h3"
          >
            Rick & Morty Image Gallery
          </Typography>
        </Container>
        <Grid container spacing={2} justifyContent="center">
          {images.map((image) => (
            <Grid
              item
              xs={12}
              sm={6}
              md={4}
              key={image.id}
              boxShadow="base"
              borderRadius="10px"
            >
              <Card>
                <CardMedia>
                  <Image
                    src={image.image}
                    alt={image.name}
                    width={0}
                    height={0}
                    sizes="100vw"
                    style={{ width: '100%', height: 'auto' }}
                  />
                </CardMedia>
                <CardContent
                  sx={{
                    bgcolor: green[900],
                  }}
                >
                  <Typography
                    variant="body2"
                    color={cyan[300]}
                    textAlign="center"
                    fontSize={24}
                    fontWeight="bold"
                  >
                    {image.name}
                  </Typography>
                </CardContent>
              </Card>
            </Grid>
          ))}
          <Grid item xs={12}></Grid>
        </Grid>
      </Box>
    </>
  );
}

export async function getServerSideProps() {
  const data = await getPhotos();
  return {
    props: {
      data,
    },
  };
}
