import Head from 'next/head';
import Image from 'next/image';
import {
  Box,
  Card,
  CardContent,
  CardMedia,
  Container,
  Divider,
  Grid,
  List,
  ListItem,
  ListItemButton,
  ListItemText,
  Typography,
} from '@mui/material';
import { cyan, green } from '@mui/material/colors';
import { Character, Episode } from '@/interfaces';
import { getAllCharacters, getAllEpisodes } from '@/lib/api';

export default function Home({
  characters,
  episodes,
}: {
  characters: Character[];
  episodes: Episode[];
}) {
  return (
    <>
      <Head>
        <title>Rick & Morty Image Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box overflow="hidden" bgcolor="#011401" minHeight="100vh">
        <Container>
          <Typography
            color={cyan[300]}
            mb="1rem"
            textAlign="center"
            variant="h3"
          >
            Rick & Morty Characters
          </Typography>
        </Container>
        <Grid container spacing={2}>
          <Grid item xs={4} md={2} padding={1}>
            <List
              sx={{
                color: cyan[300],
              }}
            >
              <ListItem>
                <ListItemText>Episodes</ListItemText>
              </ListItem>
              <Divider
                sx={{
                  borderColor: cyan[300],
                }}
              />
              {episodes.map((episode) => (
                <ListItem key={episode.id}>
                  <ListItemButton>
                    <ListItemText primary={episode.name} />
                  </ListItemButton>
                </ListItem>
              ))}
            </List>
          </Grid>
          <Grid item xs={8} md={10}>
            <Grid container columns={10} spacing={2} justifyContent="center">
              {characters.map((character) => (
                <Grid item xs={10} sm={3} md={2} key={character.id}>
                  <Card sx={{ borderRadius: 5 }}>
                    <CardMedia>
                      <Image
                        src={character.image}
                        alt={character.name}
                        width={0}
                        height={0}
                        sizes="100vw"
                        style={{ width: '100%', height: 'auto' }}
                      />
                    </CardMedia>
                    <CardContent
                      sx={{
                        bgcolor: green[900],
                      }}
                    >
                      <Typography
                        variant="body2"
                        color={cyan[300]}
                        textAlign="center"
                        fontSize={24}
                        fontWeight="bold"
                      >
                        {character.name}
                      </Typography>
                    </CardContent>
                  </Card>
                </Grid>
              ))}
              <Grid item xs={12}></Grid>
            </Grid>
          </Grid>
        </Grid>
      </Box>
    </>
  );
}

export async function getServerSideProps() {
  const characters = await getAllCharacters();
  const episodes = await getAllEpisodes();
  return {
    props: {
      characters,
      episodes,
    },
  };
}
